In [1]:
#SET
set_1 = {'a', 'b', 'c', 'd'}
type(set_1)

set

In [2]:
len(set_1)

4

In [3]:
for element in set_1:
    print(element)

b
a
c
d


In [5]:
set_1.discard('j')
set_1

{'a', 'b', 'c', 'd'}

In [6]:
set_1.discard('a')
set_1

{'b', 'c', 'd'}

In [8]:
set_1.remove('b')
set_1


{'c', 'd'}

In [18]:
set_1.clear()
set_1

set()

In [9]:
set_2 = {} ##dictionary
type(set_2)

dict

In [10]:
set_mt = set()
type(set_mt)

set

In [11]:
lst = ['1', '2']
type(lst)

list

In [12]:
cast_lst_to_set = set(lst)
cast_lst_to_set

{'1', '2'}

In [13]:
lst

['1', '2']

In [14]:
type(lst)

list

In [15]:
type(cast_lst_to_set)

set

In [16]:
'1' in lst

True

In [17]:
'3' in lst

False

In [ ]:
#Function
def func_sample():
    #code ....

In [19]:
def greet():
    print('Hi, How are you?')

In [21]:
greet()
greet()
greet()

Hi, How are you?
Hi, How are you?
Hi, How are you?


In [23]:
greet()

Hi, How are you?


In [24]:
#get the name!
#say welcome, 'name'!

def greet():
    greet_message = 'Welcome, Guest!'
    print(greet_message)

In [31]:
def greet(guest_name):
    greet_message = 'Welcome' + ' ' + guest_name 
    print(greet_message)
    

In [32]:
guest_1 = 'Miss Amini'
guest_2 = 'Miss Reyhani'
guest_3 = 'Mr Rezaei'


In [34]:
greet(guest_1)
greet(guest_2)
greet(guest_3)

Welcome Miss Amini
Welcome Miss Reyhani
Welcome Mr Rezaei


In [37]:
def greet_format(guest_name):
    greet_message = 'Welcome {0}'.format(guest_name)
    print(greet_message)
    

In [38]:
greet_format(guest_1)

Welcome Miss Amini


In [39]:
def greet_fstring(guest_name):
    greet_message = f'Welcome {guest_name}'
    print(greet_message)
    

In [40]:
greet_fstring(guest_2)

Welcome Miss Reyhani


In [43]:
#Question_Pedram

lst_q=[1,2,['salam']]


#How to check list in the another list!
print(['salam'] in lst_q)

# How to check string in to the another list!
print('salam' in lst_q)


True
False


In [47]:
for element in lst_q:
    if type(element) == list:
        print('salam' in element)

True


In [53]:
def multiplication(a, b, c):
    res = a * b * c
    print(res)
    return res

In [54]:
mult = multiplication(2, 3, 4)

24


In [55]:
print(mult)

24


In [62]:
def pot_energy(m,h, g=9.8):
    pe = m*g*h
    return pe

In [63]:
pot_energy(3, 5)

147.0

In [65]:
#def multiplication(a, b, c):
 #   res = a * b * c
  #  return res

a=2
b=5

v = lambda a, b, c=5 : a * b * c

print(v(a, b))

50


In [66]:
def func_one(a,b):
    return a*b

def func_two(func_sample):
    return func_sample*2

func_two(func_one(2, 5))
    

20

In [71]:
#string
s = 'This a CV School for a bright future'
print(s[0])
print(s[1])

print(len(s))

print('CV' in s)
#print('cv' in s)

T
h
36
True


In [73]:
name = 'Jafar '
greeting = f'Hello, {name}'
print(greeting)

Hello, Jafar 


In [74]:
name = 'Jafar '
greeting = f'Hello, {name.upper()}'
print(greeting)

Hello, JAFAR 


In [84]:
num = 200
f'{num:06}'

'000200'

In [86]:
num = 200
f'{num:0.2f}'

'200.00'

In [88]:
ticket_price = 5000
f'your ticket price is {ticket_price: 0.1f}'

'your ticket price is  5000.0'

In [95]:
# Python's owesome. She said!
txt = 'Python\'s owesome. She said'
print(txt)

Python's owesome. She said


In [96]:
#Home\Document\notebooks\table
PATH = 'Home\Document\notebooks\table'
print(PATH)

# \n : new line
# \t : tab

Home\Document
otebooks	able


In [97]:
PATH = 'Home\Document\\notebooks\\table'
print(PATH)

Home\Document\notebooks\table


In [98]:
#raw string
PATH = r'Home\Document\notebooks\table'
print(PATH)

Home\Document\notebooks\table


In [103]:
#Exception Handling

def division(a, b):
    if b==0:
        x = 'you must change the value of b'
    else:
        x = a/b
    return x

In [104]:
division(8, 2)

4.0

In [105]:
division(8, 0)

'you must change the value of b'

In [106]:
#division(8, '2')

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [107]:
#Exception Handling

def division(a, b):
    try:
        x = a/b
    except:
        x = 'you must change the value of b'
        
    return x

In [108]:
division(8, 0)

'you must change the value of b'

In [109]:
division(8, '2')

'you must change the value of b'

In [110]:
division(8, 2)

4.0

In [133]:
def division(a, b):
    a = int(a)
    b = int(b)
    try:
        x = a/b
    except ZeroDivisionError as error :
        x = error
        
       # print(x)
    except ValueError as verror:
        x = verror
    except Exception as ex:
        x = ex
        
    return x

In [134]:
division(8, 0)

ZeroDivisionError('division by zero')

In [135]:
division(8, '2')

4.0

In [136]:
#Iteration

def multiply_simple(a, b):
    return a*b

def multiply_iter(a, b):
    result = 0
    for i in range(b):
        result += a
        
    return result



In [137]:
multiply_simple(2, 3)

6

In [138]:
multiply_iter(2, 3)

6

In [142]:
#Recursion
def multiply_recur(a, b):
    if b==1:
        return a
    else:
        return (a + multiply_recur(a, b-1))

In [143]:
multiply_recur(2, 3)

6

In [144]:
#File

f=open('firstfile.txt', 'x')


In [145]:
f.write('first line')

10

In [146]:
f.close()

In [147]:
#File

f=open('firstfile.txt', 'w')
f.write('second line')
f.close()


In [148]:
#File

f=open('firstfile.txt', 'a')
f.write('third line')
f.close()


In [149]:
#File

f=open('firstfile.txt', 'a')
f.write('\n third line')
f.close()


In [150]:
import os
if os.path.exists('firstfile.txt'):
    os.remove('firstfile.txt')

In [159]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [160]:
type(arr)

numpy.ndarray

In [161]:
arr.ndim

1

In [162]:
arr.dtype

dtype('int64')

In [163]:
arr_2 = np.array([1, 2, 3], dtype=np.float16)
arr_2.dtype

dtype('float16')

In [167]:
arr_2d = np.array([
 [1, 2, 3], 
 [4, 5, 6], 
 [7, 8, 9], 
 [10, 11, 12]
])

In [168]:
arr_2d.ndim

2

In [169]:
arr_2d.shape

(4, 3)

In [171]:
arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]], 
    [['a', 'b', 'c'], 
    ['d', 'e', 'f']]   
])

In [172]:
arr_3d.ndim

3

In [173]:
arr_3d.shape

(2, 2, 3)

In [174]:
arr_zero = np.zeros((2, 3), dtype=np.int32)
arr_zero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [175]:
arr_one = np.ones((5, 4), dtype=np.int32)
arr_one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)