In [1]:
#!pip install tensorflow

In [2]:
#Basic operators of tensorflow
import tensorflow as tf

2024-07-05 19:04:36.782401: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-05 19:04:36.937031: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-07-05 19:04:36.937051: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-07-05 19:04:36.979935: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-05 19:04:37.773686: W tensorflow/stream_executor/platform/de

In [3]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

c = tf.add(a, b)
print(c)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


2024-07-05 19:04:38.964613: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-07-05 19:04:38.964663: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2024-07-05 19:04:38.964689: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mhmud): /proc/driver/nvidia/version does not exist
2024-07-05 19:04:38.965157: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
e = tf.Variable(3.0)
f = tf.Variable(7.0)

z = e*f + 2
print(z)

tf.Tensor(23.0, shape=(), dtype=float32)


In [5]:


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(32, activation='relu', input_shape=(784,)),
    Dense(10, activation= 'softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

import numpy as np 
x_train = np.random.random((1000, 784))
y_train = np.random.randint(10, size=(1000,))

model.fit(x_train, y_train, epochs=5)




# Search functional implementation of NN. 

Epoch 1/5
32/32 [==============================] - 0s 2ms/step - loss: 2.3641 - accuracy: 0.0990
Epoch 2/5
32/32 [==============================] - 0s 2ms/step - loss: 2.3010 - accuracy: 0.1140
Epoch 3/5
32/32 [==============================] - 0s 2ms/step - loss: 2.3001 - accuracy: 0.1090
Epoch 4/5
32/32 [==============================] - 0s 2ms/step - loss: 2.2984 - accuracy: 0.1130
Epoch 5/5
32/32 [==============================] - 0s 2ms/step - loss: 2.2996 - accuracy: 0.1130


In [6]:
#preprocess 
from sklearn.preprocessing import StandardScaler
import numpy as np 


data = np.array([[1, 5],[2, 3], [8, 9]])
scaler = StandardScaler()

scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[-0.86266219 -0.26726124]
 [-0.53916387 -1.06904497]
 [ 1.40182605  1.33630621]]


In [7]:
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
dataset = dataset.shuffle(buffer_size=1024).batch(32)
for batch_x, batch_y in dataset.take(2):
    print(batch_x, batch_y)

tf.Tensor(
[[0.49653396 0.29351898 0.82263649 ... 0.55158179 0.11961364 0.73218707]
 [0.70237985 0.4871595  0.14002212 ... 0.49420549 0.68840947 0.51111757]
 [0.64387692 0.23689888 0.90444259 ... 0.3765245  0.79332901 0.88099877]
 ...
 [0.80894058 0.6625855  0.15942975 ... 0.56474191 0.44696518 0.96099753]
 [0.12927889 0.56857646 0.62046365 ... 0.63886882 0.1470063  0.63446219]
 [0.30172633 0.51778536 0.28907814 ... 0.87650143 0.89267585 0.57122085]], shape=(32, 784), dtype=float64) tf.Tensor([2 8 5 0 7 8 6 9 0 0 2 8 3 9 0 4 6 9 1 4 2 7 6 5 4 2 5 3 6 3 9 1], shape=(32,), dtype=int64)
tf.Tensor(
[[0.18340838 0.38966541 0.16884829 ... 0.14950396 0.66574661 0.33169119]
 [0.5554268  0.73690435 0.70456541 ... 0.70052505 0.25959369 0.50389995]
 [0.77808152 0.58935088 0.01237286 ... 0.53544133 0.03459182 0.45756708]
 ...
 [0.49557242 0.31395694 0.30144102 ... 0.78257341 0.40629786 0.85494082]
 [0.95191423 0.87618118 0.30978587 ... 0.59642753 0.38401169 0.58565896]
 [0.8099763  0.28794124 0.36

In [8]:
#cnn
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)), 
    MaxPooling2D(pool_size=(2, 2)), 
    Flatten(), 
    Dense(64, activation='relu'), 
    Dense(10, activation= 'softmax')   
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#sparse_categorical_crossentropy vs categorical cross entropy?

x_train = np.random.random((1000, 28, 28, 1))
y_train = np.random.randint(10, size=(1000,))


model.fit(x_train, y_train, epochs=5)


#label = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
#one_hot [4] : [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
#one_hot [5] : [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

#sparse categorical cross entropy == one hot encoding + categorical ce.


Epoch 1/5
32/32 [==============================] - 1s 10ms/step - loss: 2.3491 - accuracy: 0.1050
Epoch 2/5
32/32 [==============================] - 0s 11ms/step - loss: 2.2999 - accuracy: 0.1100
Epoch 3/5
32/32 [==============================] - 0s 10ms/step - loss: 2.2916 - accuracy: 0.1330
Epoch 4/5
32/32 [==============================] - 0s 10ms/step - loss: 2.2881 - accuracy: 0.1240
Epoch 5/5
32/32 [==============================] - 0s 11ms/step - loss: 2.2661 - accuracy: 0.1800


In [9]:
#rnn
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

#this is a world for blind people, and  we have to find the light. 
#positive (0), #negative(1)

model = Sequential([
    SimpleRNN(50, activation='relu', input_shape=(10, 1)),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')


x_train = np.random.random((1000, 10, 1)) 
y_train = np.random.random((1000, 1))

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
32/32 [==============================] - 1s 3ms/step - loss: 0.1326
Epoch 2/5
32/32 [==============================] - 0s 3ms/step - loss: 0.0874
Epoch 3/5
32/32 [==============================] - 0s 3ms/step - loss: 0.0850
Epoch 4/5
32/32 [==============================] - 0s 3ms/step - loss: 0.0847
Epoch 5/5
32/32 [==============================] - 0s 3ms/step - loss: 0.0851


In [10]:
#transfer learning
#tensorflow.keras vs keras!

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

'''base_model = VGG16(weights="imagenet", include_top = False, input_shape = (224, 224, 3))
base_model.trainable = False
model = Sequential([
    
    base_model,
    Flatten(), 
    Dense(256, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_cross_entropy')


x_train = np.random.random((1000, 224, 224, 3)) 
y_train = np.random.randint(10, size=(1000, ))

model.fit(x_train, y_train, epochs=5)'''


'base_model = VGG16(weights="imagenet", include_top = False, input_shape = (224, 224, 3))\nbase_model.trainable = False\nmodel = Sequential([\n    \n    base_model,\n    Flatten(), \n    Dense(256, activation=\'relu\'),\n    Dense(10, activation=\'softmax\')\n])\n\nmodel.compile(optimizer=\'adam\', loss=\'sparse_categorical_cross_entropy\')\n\n\nx_train = np.random.random((1000, 224, 224, 3)) \ny_train = np.random.randint(10, size=(1000, ))\n\nmodel.fit(x_train, y_train, epochs=5)'

In [17]:
#custom model!

import tensorflow as tf

class CustomModel(tf.keras.Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(64, activation='relu')
        self.dense2 = tf.keras.layers.Dense(10)
    
    
    def call(self, inputs):
        x = self.dense1(inputs)
        return self.dense2(x)

    
model = CustomModel()
x_train = np.random.random((1000, 784)) 
y_train = np.random.randint(10, size=(1000, ))


optimizer = tf.keras.optimizers.Adam()
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

for epoch in range(5):
    with tf.GradientTape() as tape:
        predictions = model(x_train)
        loss = loss_fn(y_train, predictions)
    gradients = tape.gradient(loss,model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    print(f"Epoch {epoch + 1}, Loss: {loss.numpy()}")

Epoch 1, Loss: 2.6017119884490967
Epoch 2, Loss: 2.367424249649048
Epoch 3, Loss: 2.413817882537842
Epoch 4, Loss: 2.4151248931884766
Epoch 5, Loss: 2.3767426013946533


In [24]:
#evaluation
#model.compile(optimizer = optimizer, loss=loss_fn)
#loss, accuracy = model.evaluate(x_train, y_train)
#print(f" Loss: {loss}, Accuracy: {accuracy}")

In [26]:
import tensorflow as tf
import numpy as np 
x_train = np.random.random((60000, 784)).astype(np.float32)
y_train = np.random.randint(10, size=(60000,)).astype(np.int64)


dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

In [27]:
batch_size = 64
dataset = dataset.shuffle(buffer_size=1024).batch(batch_size=batch_size)\
.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

In [28]:
!pip install keras_tuner --upgrade

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.



In [ ]:
import keras
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
plt.imshow(x_train[0], cmap='gray')
plt.show()

In [ ]:
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

In [ ]:
model = keras.models.Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss="sparse_categorical_crossentropy", metrics=['accuracy'])



In [ ]:
model.fit(x_train, y_train, batch_size = 64, epochs = 1, validation_data=(x_test, y_test), verbose=1)

In [ ]:
model = build_model()
model.fit(x_train, y_train, batch_size=32, epochs=1, validation_data=(x_test, y_test), verbose=1)