In [1]:
import numpy as np

In [2]:
#speed of array processing >> list
arr_1d = np.array([8, 9, 10, 14])
type(arr_1d)

numpy.ndarray

In [3]:
arr_1d.ndim

1

In [5]:
arr_1d.shape

(4,)

In [8]:
arr_2d = np.array([[1, 2, 3, 13],[4, 5, 6, 16],[7, 8, 9, 19]])
arr_2d

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 16],
       [ 7,  8,  9, 19]])

In [9]:
arr_2d.shape

(3, 4)

In [10]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
arr_3d.shape

(1, 3, 3)

In [12]:
arr = np.array([1, 'a'])

In [13]:
arr

array(['1', 'a'], dtype='<U21')

In [14]:
#indexing & slicing
arr_sample = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [16]:
print(arr_sample[4])
print(arr_sample[10])

4
10


In [17]:
arr_sample[4:10]

array([4, 5, 6, 7, 8, 9])

In [20]:
arr_sample[4:11]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_sample[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [23]:
arr_sample[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
arr_sample_2 = np.array([2, 8, 9])
arr_sample_2[:2]

array([2, 8])

In [28]:
#2d
arr_sample_2d = np.array([[10, 11, 12, 13], [14, 15, 16, 17],
                          [18, 19, 20, 21]])
arr_sample_2d

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [29]:
arr_sample_2d.shape

(3, 4)

In [30]:
arr_sample_2d[2, 2]

20

In [31]:
arr_sample_2d[0, 3]

13

In [32]:
arr_sample_2d[:2, 1:]
#arr_sample_3d [:, :, :]

array([[11, 12, 13],
       [15, 16, 17]])

In [33]:
#View & Copy!

b = arr_sample_2d[:2, 1:]
c = arr_sample_2d[:2, 1:].copy()

print(b)
print(c)



[[11 12 13]
 [15 16 17]]
[[11 12 13]
 [15 16 17]]


In [34]:
b[0, 0]=155
b

array([[155,  12,  13],
       [ 15,  16,  17]])

In [35]:
c[0, 0]= 289
c

array([[289,  12,  13],
       [ 15,  16,  17]])

In [36]:
arr_sample_2d

array([[ 10, 155,  12,  13],
       [ 14,  15,  16,  17],
       [ 18,  19,  20,  21]])

In [37]:
y = arr_sample_2d[:2:2, 1:2:1]
y


array([[155]])

In [38]:
#math
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [40]:
#add
add_1 = a+b
add_2 = np.add(a, b)

print('add_1', add_1)
print('add_2', add_2)


add_1 [[ 6  8]
 [10 12]]
add_2 [[ 6  8]
 [10 12]]


In [41]:
#subtraction
print('first_method: ', a-b)
print('second_method: ', np.subtract(a, b))

first_method:  [[-4 -4]
 [-4 -4]]
second_method:  [[-4 -4]
 [-4 -4]]


In [42]:
#multiply
print('f_method', a*b)
print('s_method', np.multiply(a, b))

f_method [[ 5 12]
 [21 32]]
s_method [[ 5 12]
 [21 32]]


In [44]:
#division
print('f_division: ', a/b)
print('s_division: ', np.divide(a, b))

f_division:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
s_division:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [45]:
#unmached shapes
#error
c = np.array([[5, 8, 9], [14, 18, 20], [1, 0, 8]])

np.divide(a, c)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [47]:
#number of events
noe = np.array([5,6,9])

prob_e1 = noe[0] / np.sum(noe)
prob_e1

print(prob_e1)
print(np.sum(noe))

0.25
20


In [48]:
np.mean(noe)

6.666666666666667

In [49]:
np.std(noe)

1.699673171197595

In [50]:
np.var(noe)

2.888888888888889

In [51]:
np.amax(noe)

9

In [55]:
k1 = np.amin(noe)
k2 = np.min(noe)
print(k1)
print(k2)
print(type(k1))
print(type(k2))

5
5
<class 'numpy.int64'>
<class 'numpy.int64'>


In [53]:
arr_for_sorting = np.array([4, 0, 9])
np.sort(arr_for_sorting)

array([0, 4, 9])

In [56]:
#reshaping

arr_for_reshaping = np.array([[1, 2, 3], [4, 5, 6]])
arr_for_reshaping.shape


(2, 3)

In [57]:
reshaping_res = np.reshape(arr_for_reshaping, (3, 2))
reshaping_res.shape

(3, 2)

In [58]:
#error
reshaping_res_2 = np.reshape(arr_for_reshaping, (3, 3))
reshaping_res_2

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
#The End